# Generated by Django 3.2 on 2022-11-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='企业简称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('auth_type', models.SmallIntegerField(choices=[(1, '未认证'), (2, '认证中'), (3, '已认证')], default=1, verbose_name='认证类型')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='公司全称')),
                ('unique_id', models.CharField(max_length=64, verbose_name='信用代码')),
                ('licence_path', models.CharField(max_length=64, verbose_name='营业执照')),
                ('leader', models.CharField(max_length=64, verbose_name='法人')),
                ('leader_identity', models.CharField(max_length=64, verbose_name='法人身份')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='公司')),
            ],
        ),
    ]
