# Generated by Django 3.2 on 2022-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
