# Generated by Django 3.2 on 2022-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20221211_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyauth',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='审核备注'),
        ),
    ]
