# Generated by Django 3.2 on 2022-12-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_companyauth_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='可用余额'),
        ),
        migrations.AddField(
            model_name='company',
            name='freeze_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='不可用余额'),
        ),
    ]
