# Generated by Django 3.2 on 2022-12-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_administrator_transactionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='ali_account',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='提现支付宝'),
        ),
    ]
