# Generated by Django 3.2 on 2022-12-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20221225_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.SmallIntegerField(choices=[(-1, '提现'), (1, '充值')], verbose_name='转账类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='金额')),
                ('trans_id', models.CharField(db_index=True, max_length=64, verbose_name='订单号')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('trans_remark', models.TextField(blank=True, null=True, verbose_name='交易备注')),
                ('pay_status', models.SmallIntegerField(choices=[(-1, '已取消'), (0, '未支付'), (1, '已支付')], default=0, verbose_name='支付状态')),
                ('auditor_status', models.SmallIntegerField(blank=True, choices=[(-1, '审核失败'), (0, '待审核'), (1, '审核通过')], null=True, verbose_name='审核')),
                ('auditor_datetime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('auditor_remark', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.administrator', verbose_name='审核员')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='供应商')),
            ],
        ),
    ]
